"""СрфChange table name chalenge -> challenges

Revision ID: 210fc04652dd
Revises: 71ea40782dcc
Create Date: 2026-03-26 10:38:17.336340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '210fc04652dd'
down_revision: Union[str, Sequence[str], None] = '71ea40782dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('PUBLIC', 'PRIVATE', 'BLOCKED', 'ON_APILATION', name='challengestatusenum'), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('dislikes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('card_description', sa.String(length=1000), nullable=False),
    sa.Column('card_picture_url', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_challenges_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges')),
    sa.UniqueConstraint('name', name=op.f('uq_challenges_name'))
    )
    op.create_table('challenge_tags',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_tags_challenge_id_challenges')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_challenge_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('challenge_id', 'tag_id', name=op.f('pk_challenge_tags'))
    )
    op.drop_table('chalenge_tags')
    op.drop_table('chalenges')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chalenges',
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PUBLIC', 'PRIVATE', 'BLOCKED', 'ON_APILATION', name='chalengestatusenum'), autoincrement=False, nullable=False),
    sa.Column('description', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dislikes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('card_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('card_picture_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_chalenges_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges')),
    sa.UniqueConstraint('name', name=op.f('uq_chalenges_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('chalenge_tags',
    sa.Column('chalenge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chalenge_id'], ['chalenges.id'], name=op.f('fk_chalenge_tags_chalenge_id_chalenges')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_chalenge_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('chalenge_id', 'tag_id', name=op.f('pk_chalenge_tags'))
    )
    op.drop_table('challenge_tags')
    op.drop_table('challenges')
    # ### end Alembic commands ###
