"""Remove unique constraiment fomr name field

Revision ID: ddb873a23bc0
Revises: 210fc04652dd
Create Date: 2026-03-26 11:02:35.414151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb873a23bc0'
down_revision: Union[str, Sequence[str], None] = '210fc04652dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_challenges_name'), 'challenges', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_challenges_name'), 'challenges', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
