"""Remove user_id and status fields from tag model

Revision ID: 04fc9adb75df
Revises: ddb873a23bc0
Create Date: 2026-03-29 11:06:30.649798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04fc9adb75df'
down_revision: Union[str, Sequence[str], None] = 'ddb873a23bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'status')
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tags', sa.Column('status', postgresql.ENUM('ACTIVE', name='tagstatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
