networks:
  backend:
    name: backend
    driver: bridge

include:
  - infra/rabbitmq/docker-compose.yaml
  - infra/gateway/docker-compose.yaml
  #- infra/nginx/docker-compose.yaml

  - services/users/docker-compose.yaml
  - services/games/docker-compose.yaml
  - services/challenges/docker-compose.yaml
  - services/social/docker-compose.yaml
  #- services/recommendations/docker-compose.yaml

  #- frontend/docker-compose.yaml
