services:
  challenges-db:
    image: postgres:16
    container_name: challenges-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5
    networks:
      - challenges-private
    volumes:
      - challenge-db:/var/lib/postgresql/data 

  challenges-redis:
    image: redis:7
    container_name: challenges-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    networks:
      - challenges-private

  challenges-api:
    build: .
    container_name: challenges-api
    env_file:
      - .env
      - ../../.env
    depends_on:
      challenges-redis:
        condition: service_healthy
    networks:
      - backend
      - challenges-private

networks:
  challenges-private:

volumes:
  challenge-db:
