services:
  challenges-db:
    image: postgres:16
    container_name: challenges-db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      retries: 5
    networks:
      - challenges-private
    volumes:
      - challenge-db:/var/lib/postgresql/data 

  challenges-redis:
    image: redis:7
    container_name: challenges-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
    networks:
      - challenges-private

  challenges-migrations:
    build: .
    container_name: challenges-migrations
    working_dir: /app
    command: ["alembic", "-c", "alembic.ini", "upgrade", "head"]
    env_file:
      - .env
      - ../../.env
    depends_on:
      challenges-db:
        condition: service_healthy
    networks:
      - challenges-private
    restart: "no"

  challenges-api:
    build: .
    container_name: challenges-api
    env_file:
      - .env
      - ../../.env
    depends_on:
      challenges-db:
        condition: service_healthy
      challenges-redis:
        condition: service_healthy
      challenges-migrations:
        condition: service_completed_successfully
    networks:
      - backend
      - challenges-private
    volumes:
      - challenges-pics:/app/challenges_pics

networks:
  challenges-private:

volumes:
  challenge-db:
  challenges-pics:
