"""Initial migration. Add models for comments and statuse

Revision ID: 136c4d53481c
Revises: 
Create Date: 2026-02-16 08:21:57.225623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136c4d53481c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('author_name', name=op.f('uq_games_author_name')),
    sa.UniqueConstraint('name', name=op.f('uq_games_name'))
    )
    op.create_table('chalenges',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_chalenges_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges'))
    )
    op.create_table('chalenges_comments',
    sa.Column('chalenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('dificulty_rate', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('dislikes_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('dificulty_rate >= 0 AND dificulty_rate <= 5', name=op.f('ck_chalenges_comments_check_chalenge_comment_dificulty_rate_range')),
    sa.CheckConstraint('dislikes_count >= 0', name=op.f('ck_chalenges_comments_check_chalenge_comment_dislikes_positive')),
    sa.CheckConstraint('likes_count >= 0', name=op.f('ck_chalenges_comments_check_chalenge_comment_likes_positive')),
    sa.ForeignKeyConstraint(['chalenge_id'], ['chalenges.id'], name=op.f('fk_chalenges_comments_chalenge_id_chalenges')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['chalenges_comments.id'], name=op.f('fk_chalenges_comments_parent_comment_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges_comments'))
    )
    op.create_table('chalenges_comments_dislikes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['chalenges_comments.id'], name=op.f('fk_chalenges_comments_dislikes_comment_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges_comments_dislikes'))
    )
    op.create_table('chalenges_comments_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['chalenges_comments.id'], name=op.f('fk_chalenges_comments_likes_comment_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges_comments_likes'))
    )
    op.create_table('chalenges_dislikes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chalenge_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['chalenge_id'], ['chalenges_comments.id'], name=op.f('fk_chalenges_dislikes_chalenge_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges_dislikes'))
    )
    op.create_table('chalenges_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chalenge_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['chalenge_id'], ['chalenges_comments.id'], name=op.f('fk_chalenges_likes_chalenge_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chalenges_likes'))
    )
    op.create_table('users_chalenges_statuses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chalenge_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DROPED', 'COMPLETED', 'IN_PROGRESS', 'FAVOURITE', name='userchalengestatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['chalenge_id'], ['chalenges_comments.id'], name=op.f('fk_users_chalenges_statuses_chalenge_id_chalenges_comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_chalenges_statuses'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_chalenges_statuses')
    op.drop_table('chalenges_likes')
    op.drop_table('chalenges_dislikes')
    op.drop_table('chalenges_comments_likes')
    op.drop_table('chalenges_comments_dislikes')
    op.drop_table('chalenges_comments')
    op.drop_table('chalenges')
    op.drop_table('games')
    # ### end Alembic commands ###
