@Games.Api_HostAddress = http://localhost:5017
@BearerToken = your-jwt-token

GET {{Games.Api_HostAddress}}/api/library/me
Accept: application/json
Authorization: Bearer {{BearerToken}}

###

POST {{Games.Api_HostAddress}}/api/library/me/import/steam
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
  "profileId": "76561198000000000",
  "includePlayedFreeGames": true,
  "importedGamesStatus": 0
}

###

POST {{Games.Api_HostAddress}}/api/library/me/import/epic-games
Content-Type: application/json
Authorization: Bearer {{BearerToken}}

{
  "accountId": "your-epic-account-id",
  "importedGamesStatus": 0
}

###
